### ISSUE TITLE
Service worker registration broken on deep URLs

### ISSUE THREAD

**Issue by rafaelgieschke** [ikreymer/proxy-wabac#1]
Very cool demo, @ikreymer! :+1: :+1:

But if you visit https://proxy-wabac.webrecorder.net/test/ first, it breaks with:

```
Uncaught (in promise) TypeError: Failed to register a ServiceWorker for scope ('https://proxy-wabac.webrecorder.net/test/') with script ('https://proxy-wabac.webrecorder.net/test/sw.js?root=proxytest&proxy=1'): A bad HTTP response code (404) was received when fetching the script.
```

(probably got broken by <https://github.com/ikreymer/proxy-wabac/commit/e602ae98d1b58fcda15d81bef8648ff283901741> as `ServiceWorkerContainer.register()` is relative to `location`).

**Comment by ikreymer** [comment]
Heh, this is what I get for last-min changes.. thought I could make it work on a non-root path, should revert that change.

**Comment by ikreymer** [comment]
Fixed now. Shows the standard error messages, but important thing is that the service worker still takes over.
